title: Chuchen (Leo) Xiong # your name (or website title) here
logo: "/images/photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <p align="center">
  UMN MSc in Business Analytics
  
  Hi, I am Chuchen Xiong, a graduate student pursuing data science career. In the gap year after my college, I was interested in using data
  to explore the unknown, tell a story, and make an impact when I was an intern in China Merchant Bank and Accenture Strategy. 
  <br><br>
  </p>
  
  
  <a href="mailto:xion2022@umn.edu">Email</a>
  <br><br>
  <a href="https://www.linkedin.com/in/chuchen-leo-xiong/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/Xion6cc">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-167357228-1 # your Google Analytics tracking ID here
