title: Chuchen (Leo) Xiong # your name (or website title) here
logo: "/images/Photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="mailto:xion2022@umn.edu">Email</a>
  <a href="https://www.linkedin.com/in/chuchen-leo-xiong/">LinkedIn</a>
  <a href="https://github.com/Xion6cc">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-167357228-1 # your Google Analytics tracking ID here
